language: cpp

compiler:
- clang
- gcc

env:
- QT_BASE=58

before_install:
- if [ "$QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi

install:
- sudo apt-get update
- sudo apt-get install build-essential libxen-dev
- if [ "$QT_BASE" = "58" ]; then sudo apt-get install qt58base; source /opt/qt58/bin/qt58-env.sh; fi
- git clone git://github.com/qtmark/qmjson.git
- pushd qmjson && git checkout c503e3a1f77b782814aa929d4ecd7aa2d1ce1c2d && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX" && make -j && sudo make install && popd

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX"
- make -j
- ./tests/qtdbd-unittests/qtdbd-unittests
