language: cpp

compiler:
- clang
- gcc

env:
- QT_BASE=54
- QT_BASE=55

before_install:
- if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt541 -y; fi
- if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt55 -y; fi

install:
- sudo apt-get update
- sudo apt-get install build-essential
- if [ "$QT_BASE" = "54" ]; then sudo apt-get install qt54base; source /opt/qt54/bin/qt54-env.sh; fi
- if [ "$QT_BASE" = "55" ]; then sudo apt-get install qt55base; source /opt/qt55/bin/qt55-env.sh; fi

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX"
- make -j
- ./tests/qtdbd-unittests/qtdbd-unittests
