language: cpp

compiler:
- clang
- gcc

env:
- QT_BASE=54
- QT_BASE=551
- QT_BASE=561
#- QT_BASE=562
#- QT_BASE=57

before_install:
- if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542 -y; fi
- if [ "$QT_BASE" = "551" ]; then sudo add-apt-repository ppa:beineri/opt-qt551 -y; fi
- if [ "$QT_BASE" = "561" ]; then sudo add-apt-repository ppa:beineri/opt-qt561 -y; fi
- if [ "$QT_BASE" = "562" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-xenial -y; fi
- if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt57-xenial -y; fi

install:
- sudo apt-get update
- sudo apt-get install build-essential libxen-dev
- if [ "$QT_BASE" = "54" ]; then sudo apt-get install qt54base; source /opt/qt54/bin/qt54-env.sh; fi
- if [ "$QT_BASE" = "551" ]; then sudo apt-get install qt55base; source /opt/qt55/bin/qt55-env.sh; fi
- if [ "$QT_BASE" = "561" ]; then sudo apt-get install qt56base; source /opt/qt56/bin/qt56-env.sh; fi
- if [ "$QT_BASE" = "562" ]; then sudo apt-get install qt56base; source /opt/qt56/bin/qt56-env.sh; fi
- if [ "$QT_BASE" = "57" ]; then sudo apt-get install qt56base; source /opt/qt57/bin/qt57-env.sh; fi
- git clone git://github.com/qtmark/qmjson.git
- pushd qmjson && git checkout c503e3a1f77b782814aa929d4ecd7aa2d1ce1c2d && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX" && make -j && sudo make install && popd

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX"
- make -j
- ./tests/qtdbd-unittests/qtdbd-unittests
