/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a db_adaptor ../db.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DB_ADAPTOR_H
#define DB_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.citrix.xenclient.db
 */
class DbInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.citrix.xenclient.db")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.citrix.xenclient.db\">\n"
"    <method name=\"read\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"read_binary\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"out\" type=\"ay\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"write\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"dump\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"inject\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"list\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"rm\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"exists\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"ex\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DbInterfaceAdaptor(QObject *parent);
    virtual ~DbInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString dump(const QString &path);
    bool exists(const QString &path);
    void inject(const QString &path, const QString &value);
    QStringList list(const QString &path);
    QString read(const QString &path);
    QByteArray read_binary(const QString &path);
    void rm(const QString &path);
    void write(const QString &path, const QString &value);
Q_SIGNALS: // SIGNALS
};

#endif
